[package]
name = "app"
edition = "2024.beta"
license = "MIT"
authors = ["Satyam Bansal <satyambnsal@gmail.com>"]

[dependencies]
enclave = { local = "../enclave" }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework/", rev = "mainnet-v1.48.4" }


[addresses]
app = "0x0"
treasury = "0xc647dfdb8d8b575809902c9b86a26b6ace9f9271dfe5385468f503833a237177"

[dev-dependencies]


[dev-addresses]
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.
# alice = "0xB0B"
